# Generated by Django 3.1.5 on 2021-10-31 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_tasks_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='task_user',
        ),
    ]
