# Generated by Django 3.1.5 on 2021-10-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_remove_tasks_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_user',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
